spring.application.name=be



spring.datasource.url=jdbc:mysql://localhost:3307/ 
spring.datasource.username=root
spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-request-size=10MB

# VNPAY CONFIG
# ===== VNPAY SANDBOX =====
vnpay.tmn-code=1PEP594H
vnpay.hash-secret=AGSVX4KNUCYNDVCNHJC6O0CCEOVK5CW1

vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/vnpay/return


# Thay th? b?ng Key c?a b?n
gemini.api.key=AIzaSyAVvNXByWrApsN0ZDYagpap18YhOQ1r61k
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/geamini-pro:generateContent

# JWT CONFIG
jwt.secret=mySuperSecretKeyForJWTTokenSigningMustBeAtLeast32BytesLong!
jwt.expiration-ms=86400000
